/*******************************
  公众号:木木IOS分享
关注了解更多新科技！！！
Ty
脚本名称:Ty
使用声明：️此脚本仅供学习与交流，
        请勿转载与贩卖！️️️
群1077223830
*******************************
[rewrite_local]
^http[s]?:\/\/files.yuchenglw.com\/Index\/index?t=*.+$ url script-response-body .js
[mitm] 
hostname = *..*
*******************************
Surge

[Script]
^http[s]?:\/\/files.yuchenglw.com\/Index\/index?t=*.+$ requires-body=1,max-size=0,script-path=.js

[MITM]
hostname = *..*

*******************************/
var obj = JSON.parse($response.body);
    obj. <!--  -->=  <!--  -->;
    $done({body: JSON.stringify(obj)});
